MENU_BACKGROUND_DB = './backgrounds'
MUSIC_DB = './music_list'
SCORE_DB = './scores_videos'
WND_NAME = 'Karol-Oke'
MUSIC_BAR = './overlay/player_bar.png'
ICONS_SET = './icons/'
SCORE_BACKGROUND = './score_backgrounds'
